Topl/protobuf-specs

protobuf/bifrost/bifrost_rpc.proto
protobuf/models/address.proto
protobuf/models/block.proto
protobuf/models/box.proto
protobuf/models/certificate.proto
protobuf/models/common.proto
protobuf/models/proof.proto
protobuf/models/proposition.proto
protobuf/models/transaction.proto
protobuf/models/verification_key.proto

- Specifies the initial set of proto definitions within the Topl ecosystem
- Imports the initial set of .proto definitions from the [Bifrost repo](https://github.com/Topl/Bifrost/tree/tetra/topl-grpc/src/main/protobuf)
- Added documentation/comments
These definitions are preliminary and are expected to change in the near future.  We will eagerly include the current definitions in `main` to allow for linking/URLs during conversations/planning.

Preliminary Models and Bifrost RPC Spec

---

protobuf/bifrost/bifrost_rpc.proto

- Adds a new RPC to the Bifrost/Node service which retrieves the block ID associated with a requested "depth"
- New `rpc` definition, with new Request and Response `message` types.
- Tested in Bifrost [implementation](https://github.com/Topl/Bifrost/pull/2493)
- BN-594

Added "FetchBlockIdAtDepth" RPC

---

genus/genus_models.proto
genus/genus_rpc.proto
models/block.proto
models/box.proto
models/transaction.proto
node/bifrost_rpc.proto
run_protocol_compilers.sh

- `optional` proto3 syntax is experimental and not supported in all target languages
- `optional` proto3 syntax does not modify behavior anyway; it's mostly just a documentation syntax
- Remove uses of `optional` syntax, replace with a comment
N/A
N/A

Remove "optional" Syntax

---

build/scala/build.sbt
jitpack.yml

- ScalaPB has a code generator option which flattens out all message definitions into its declared package scope instead of further nesting by file name
- (This option was used in Bifrost but was not carried over here to protobuf-specs)
- Added the option
N/A
N/A

Scala FlatPackage

---

brambl/models/builders.proto

During the creation of brambl builders in TSDK-221, 2 new models were introduced. This PR is to move them to PB
Put OutputBuildRequest and InputBuildRequest under brambl.models.builders with a comment explaining each
- Ran `cd build/scala` and `sbt publishLocal` => local build successful
- After pushing, I used JitPack in my local quivr4s branch to consume these models
* Related to #TSDK-221
* Closes #TSDK-223

TSDK-223 Added new models used by the brambl builders

---

build/scala/build.sbt

- SBT includes the original source code with the compiled code by default when publishing its artifacts
- But it does **not** include _generated_ source code, for example, code generated by `protoc`
- Add generated source code to the published artifact
- Checked locally in the Bifrost repository:
N/A

SBT Publish protobuf-specs Sources

---

proto/consensus/models/operational_certificate.proto

Protobuf-Specs-OperationalCertificate-Rules
- required and lengths rules
```
final case class OperationalCertificate(
parentVK: co.topl.consensus.models.VerificationKeyKesProduct,
parentSignature: co.topl.consensus.models.SignatureKesProduct,
childVK: co.topl.crypto.models.VerificationKeyEd25519,
childSignature: co.topl.crypto.models.SignatureEd25519,
```
```
object SignatureKesProductValidator extends scalapb.validate.Validator[co.topl.consensus.models.SignatureKesProduct] {
def validate(input: co.topl.consensus.models.SignatureKesProduct): scalapb.validate.Result =
co.topl.consensus.models.SignatureKesSumValidator.validate(input.superSignature) &&
co.topl.consensus.models.SignatureKesSumValidator.validate(input.subSignature) && …
```

BN-820-Protobuf-Specs-OperationalCertificate-Rules

---

proto/consensus/models/block_id.proto

Add length rule
> bytes value = 1 [(validate.rules).bytes.len = 32];
Generated Code:
```
package co.topl.consensus.models
object BlockIdValidator extends scalapb.validate.Validator[co.topl.consensus.models.BlockId] {
def validate(input: co.topl.consensus.models.BlockId): scalapb.validate.Result =
scalapb.validate.Result.run(io.envoyproxy.pgv.BytesValidation.length("BlockId.value", input.value, 32))
}
```
https://topl.atlassian.net/browse/BN-820

BN-820-Protobuf-Specs-OperationalCertificate-Len-Rule

---

proto/brambl/models/common.proto

Add model to encapsulate ImmutableBytes
Added ImmutableBytes in the Brambl layer to mirror the  [SignableBytes](https://github.com/Topl/protobuf-specs/blob/main/proto/quivr/models/shared.proto#L75) in the quivr layer. 
- Ran `cd build.scala` and `sbt publishLocal` and verified library built as expected with new model
* Part of TSDK-287

Added ImmutableBytes definition

---

proto/consensus/models/slot_data.proto

slotData rules
```scala
package co.topl.consensus.models
object SlotDataValidator extends scalapb.validate.Validator[co.topl.consensus.models.SlotData] {
def validate(input: co.topl.consensus.models.SlotData): scalapb.validate.Result =
co.topl.consensus.models.SlotIdValidator.validate(input.slotId) &&
co.topl.consensus.models.SlotIdValidator.validate(input.parentSlotId) &&
scalapb.validate.Result.run(io.envoyproxy.pgv.BytesValidation.length("SlotData.rho", input.rho, 64)) &&
scalapb.validate.Result.run(io.envoyproxy.pgv.BytesValidation.length("SlotData.eta", input.eta, 32))
}
```
closes https://topl.atlassian.net/browse/BN-830

slotData rules

---

proto/consensus/models/block_header.proto

blockheader rules
```scala
package co.topl.consensus.models
object BlockHeaderValidator extends scalapb.validate.Validator[co.topl.consensus.models.BlockHeader] {
def validate(input: co.topl.consensus.models.BlockHeader): scalapb.validate.Result =
co.topl.consensus.models.BlockIdValidator.validate(input.parentHeaderId) &&
co.topl.consensus.models.EligibilityCertificateValidator.validate(input.eligibilityCertificate) &&
co.topl.consensus.models.OperationalCertificateValidator.validate(input.operationalCertificate) &&
scalapb.validate.Result.run(io.envoyproxy.pgv.BytesValidation.length("BlockHeader.address", input.address, 32))
}
```
* closes https://topl.atlassian.net/browse/BN-829

blockheader rules

---

proto/node/services/bifrost_rpc.proto

BN-836-nodeRules
```
object FetchBlockBodyReqValidator extends scalapb.validate.Validator[co.topl.node.services.FetchBlockBodyReq] {
def validate(input: co.topl.node.services.FetchBlockBodyReq): scalapb.validate.Result =
co.topl.consensus.models.BlockIdValidator.validate(input.blockId)
}
```

BN-836-nodeRules

---

CHANGELOG.md
proto/node/models/block.proto

Add node models Block contraints validations
header and body are now required
```
@SerialVersionUID(0L)
final case class Block(
header: co.topl.consensus.models.BlockHeader,
body: co.topl.node.models.BlockBody,
unknownFields: _root_.scalapb.UnknownFieldSet = _root_.scalapb.UnknownFieldSet.empty
) extends scalapb.GeneratedMessage with scalapb.lenses.Updatable[Block] {
```
*

Add node models Block contraints validations

---

proto/genus/genus_models.proto
proto/genus/genus_rpc.proto

Protobuf specs are currently using the older models, which should be replaced by the new ones.
- Updated genus_rpc.proto
- Updated genus_models.proto
Protobuf compiler runs correctly and the project structure looks correct.
* TSDK-319

TSDK-319 | Genus protobuf migration

---

proto/quivr/models/shared.proto

```
sbt:quivr4s> test
[info] compiling 1 Scala source to /home/fernando/topl/quivr4s/target/scala-2.13/test-classes ... signature1.value.length
64
co.topl.quivr.QuivrCompositeOpsTests:
==> X co.topl.quivr.QuivrCompositeOpsTests.An and proposition must evaluate to true when both the verification of both proofs is true  0.338s scalapb.validate.FieldValidationException: Validation failed: Witness.value: length must be 32 - Got [91, 85, -114, -68, 10, -121, -30, -36, 112, 59, -69, 118, -13, 115, -9, 114, -9, -125, -54, 7, -8, 31, -15, 51, -83, 40, -100, 21, 53, 37, -112, 13, 101, 52, -76, 43, 14, 113, 38, -57, 107, 126, -91, 14, -109, 120, 105, 31, 29, 77, 40, 114, 55, -97, -90, -117, -114, 0, 21, -123, -22, 48, 21, 8]
```
update witness size
*

Witness size should 64

---

proto/brambl/models/address.proto

make Address Index Field Optional
```scala
final case class Address(
network: _root_.scala.Int = 0,
ledger: _root_.scala.Int = 0,
index: _root_.scala.Option[_root_.scala.Int] = _root_.scala.None,    // <<< Changed
id: co.topl.brambl.models.Identifier,
unknownFields: _root_.scalapb.UnknownFieldSet = _root_.scalapb.UnknownFieldSet.empty
) extends scalapb.GeneratedMessage with scalapb.lenses.Updatable[Address]
```

makeAddressIndexFieldOptional

---

proto/quivr/models/shared.proto

Add support for ExtendedEd25519 specific keys 
Updated VerificationKey and SigningKey to be one of Ed25519 or ExtendedEd25519.
TODO: 
- reflect the changes in quivr4s
- reflect the changes in BramblSc
- reflect the changes in Bifrost
- ensured dart compiles (`build/dart/compile_protos.sh`)
- ensured scala compiles (`buils/scala/sbt publishLocal`)
- tested that the changes accurately reflect when used (tested it out in a local quivr4s build)
* Part of TSDK-358

Added Support for ExtendedEd25519 Keys

---

proto/genus/genus_rpc.proto

Genus Rpc contains 2 services, one of them is prefixed with  Genus, the other not,  this change removes the Genus prefix.
- GenusFullBlockService ->  FullBlockService
- TransactionService

Naming refactor on services

---

CHANGELOG.md
README.md
proto/brambl/models/address.proto
proto/brambl/models/box/attestation.proto
proto/brambl/models/box/lock.proto
proto/brambl/models/evidence.proto
proto/brambl/models/identifier.proto
proto/genus/genus_models.proto
proto/genus/genus_rpc.proto
proto/node/models/block.proto
proto/node/services/bifrost_rpc.proto
proto/quivr/models/shared.proto

- Interacting with Transaction IDs is cumbersome due to the nested types
- Separate types for 32/64-length values adds overhead to the code
- Create TransactionId, LockId, and AccumulatorRootId.  Remove Identifier super-type.
- Remove Address super-type
- Remove 32/64 distinctions for types, collapsed into a single type at 32-bytes
- Implemented in Quivr4s, BramblSc, and Bifrost
- #BN-963

Create TransactionId, Remove 32/64 Distinctions

---

proto/genus/genus_models.proto
proto/genus/genus_rpc.proto

Genus Transaction Service, QueryByAddressRequest
- QueryByAddressRequest accepts a single LockAddress
- TxoAddressResponse returns a map<TransactionOutputAddress, Txo>
- Txo returns an UnspentTransactionOutput and TxoState
TODO

QueryByAddressRequest rework

---

CHANGELOG.md
proto/brambl/models/transaction/io_transaction.proto
proto/consensus/models/block_header.proto

- Transactions and Block Headers are self-identifying, but sometimes it is convenient to include their IDs in the underlying models to avoid re-computation
- Add `transactionId` to IoTransaction
- Add `headerId` to BlockHeader
- Implemented in BramblSc and Bifrost
- #BN-995

Add transactionId and headerId Fields

---

proto/genus/genus_rpc.proto

for this initial implementation,  "txo spent / txo unspent / txo pending / txo total"
optional p2:
The Annulus team may also want "Total LVLs" and "Total TOPLs" at some point.
Could also do statistics like "Unique Stakers"

BN-1026-implement-network-metrics-p-1

---

proto/genus/genus_rpc.proto

Add empty blocks count to NetworkStats
- Supports "total blocks with transactions in them"
https://topl.atlassian.net/browse/BN-1044

BN-1044 block Stats

---

.github/release-drafter.yml
.github/workflows/deploy.yml
.github/workflows/release_drafter.yml
build/scala/build.sbt
build/scala/project/plugins.sbt

Tooling for publishing Protobuf specs to Maven
- Added Release drafter workflow
- Added publish workflow (added the necessary secrets to the repo)
- note: version is removed from build.sbt since sbt-ci-release says not to set version as it is handled by sbt-dynver
- Ensured publish workflow is successful > Github Actions ran successfully and artifact snapshot exists in sonatype repo
- Ensured artifact snapshot is accessible from coursier > Ran `cs fetch co.topl:protobuf-fs2_2.13:0.0.0+1-955197d7-SNAPSHOT -r https://s01.oss.sonatype.org/content/repositories/snapshots` > fetch from sonatype repo was successful 
- Ensured artifact snapshot  is usable from another project >  In the quivr4s repo, updated the protobuf-specs dependency to refer to the sonatype snapshot > the snapshot artifact is …

TSDK-498 Maven deploy tooling

---

CHANGELOG.md
proto/brambl/models/box/value.proto
proto/consensus/models/block_header.proto
proto/consensus/models/staking.proto
proto/consensus/models/staking_address.proto

- Previously, Staking Registration and Staking Tokens were decoupled which could lead to cases where users may register with 0 stake, or users may assign stake to a registration that does not exist
- This PR combines Registration with the Staking Token to prevent such cases
- Rename staking_address.proto to staking.proto, create StakingRegistration and ActiveStaker messages
- Remove Registration Box Value
- Replace "stakingAddress" field in Topl Box value with a StakingRegistration
- Implemented in BramblSc and Bifrost
- #BN-770

Staking/Registration Changes

---

proto/consensus/models/block_header.proto
proto/consensus/models/protocol_version.proto

- `firstDigit` Significant hard fork/version change/consensus rule set change
- `secondDigit` Feature additions, bugs fixing hard forks, minor hard forks, significant soft forks, interface should
work the same
- `thirdDigit` Minor changes
Grammar:
```
<valid version> ::= <version>
<version> ::= <firstDigit> "." <secondDigit> "." <thirdDigit>
<firstDigit> ::= <digit>
<secondDigit> ::= <digit>
<thirdDigit> ::= <digit>
<digit> ::= "0" | "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9"
```

BN-1126-blockVersion

---

.github/workflows/_protoc_build.yml
.github/workflows/deploy.yml

- Snapshot releases do not publish under the proper version on GitHub Actions
- Update the GitHub workflows to fetch the entire git history, thus fetching all available tags as well
- Correct version [here](https://github.com/Topl/protobuf-specs/actions/runs/5785945389)
N/A

Fix Snapshot Versions

---

CHANGELOG.md
proto/genus/genus_models.proto
proto/node/models/block.proto

- Block Producers need an incentive to run a node
- This incentive is captured as a reward, which is the accumulation of all fees paid in the block's transactions
- This reward is stored in the ledger as an additional Transaction, but it is encoded in a BlockBody as a separate field
- Update BlockBody and FullBlockBody to contain an additional reward transaction field
- Also updated Genus BlockData to contain a FullBlockBody
- Implemented in Bifrost
- #BN-1140

BlockBody Reward

---

CHANGELOG.md
proto/brambl/models/box/asset.proto
proto/brambl/models/box/value.proto
proto/brambl/models/datum.proto
proto/brambl/models/event.proto
proto/brambl/models/identifier.proto
proto/brambl/models/transaction/io_transaction.proto

TAMv2 Assets
A TAMv2 asset is a token that has the following attributes:
- A group identifier
- A series identifier
-  A quantity
Asset Lifecycle
- Mint a group constructor token
- Mint a series constructor token (this can be done in the same transaction as the group constructor is minted)
- Mint an asset token using the group and series constructor token just minted.
This PR is linked to the following PRs, and only group constructor token, with empty series was implemented.
- https://github.com/Topl/protobuf-specs/pull/78
- https://github.com/Topl/BramblSc/pull/86
- Implement models step1:  **group constructor token**
- Implement models step1:  **series constructor token**
protobuf complie
step 1: https://topl.atlassian.net/browse/BN-909

BN-1138/113434 group and series asset token

---

.github/workflows/_protoc_build.yml
build/scala/build.sbt
build/scala/project/plugins.sbt
jitpack.yml

Scala 3 is not able to publish artifacts and is blocking releases.
"2023-08-29 16:30:40.382Z  info [SonatypeClient]     Failed: pom-staging, failureMessage:Invalid POM: /co/topl/protobuf_2.13/2.0.0-alpha4/protobuf_2.13-2.0.0-alpha4.pom: Project URL missing, License information missing, Developer information missing  - (SonatypeClient.scala:386)"
revert and fix later

revert scala3 cross publish is not working

---

proto/brambl/models/transaction/io_transaction.proto

include minting Assest Statements 
All Asset Minting Statements  are attached to the transaction.](https://github.com/Topl/tips/tree/main/TIP-0003#minting-of-an-asset-token)

include mintingAssestStatements

---

proto/google/health_check.proto
proto/google/models/health_models.proto
proto/google/services/health_rpc.proto

Add health check proto. 
The proto comes from: https://github.com/grpc/grpc/blob/master/doc/health-checking.md
Built locally, implemented in Bifrrost, deployed to GKE and ensured that the `grpc` liveliness/readiness probes succeeded.

[BN-1018] Add gRPC Health Check Proto

---

proto/node/models/p2p.proto

Change known host peer requirements to allow transfer hostname instead of ip name

Change requerments for host known name

---

build/scala/build.sbt
build/scala/project/plugins.sbt

- Some clients may benefit from scala3 libraries
- Add crossbuild support
- `publishLocal` publishes scala2 and scala3 artifacts
- GitHub Actions publish: https://github.com/Topl/protobuf-specs/actions/runs/8754864752/job/24027730619
- Note: There are a lot of "warnings" in the generated code for scala3
N/A

Scala3 Support

---

proto/node/services/regtest.proto

- Adds proto definitions for the Regtest RPC service
- New file containing new service definition
- RPC "MakeBlocks"
- Successfully implemented in Bifrost
#BN-1477

Regtest RPC
