protobuf/genus/genus_models.proto, protobuf/genus/genus_rpc.proto, run_protocol_compilers.cmd
This pull request incorporates refinements discovered when documenting the Brambl query API for Genus.
For Jira ticket TSDK-46
=> Tsdk 46 create orient db database 4

README.md, protobuf/node/bifrost_rpc.proto, run_protocol_compilers.sh
This PR includes latest changes of Node, into this repo.
=> BN-582-2313 v1

models/box.proto, models/transaction.proto
Add minting, like current version of bifrost node
=> Bn 582 2313 submodule integration add minting

jitpack.yml
- JitPack is a service that automatically builds and "publishes" maven-like artifacts to its own separate resolver
- This allows us to quickly iterate and make changes to our Scala codebases in multiple repositories
- Added a jitpack.yml file which runs the SBT steps from the `build/scala` directory
- Build was [successful](https://jitpack.io/#Topl/protobuf-specs/1513586ac9)
N/A
=> Custom jitpack.yml File

CHANGELOG.md, node/services/bifrost_rpc.proto
SynchronizationTraversalRes should return BlockIds
SynchronizationTraversalRes should return BlockIds
[BN813](https://topl.atlassian.net/browse/BN-813)
=> SynchronizationTraversalRes should return BlockIds

proto/quivr/models/proof.proto, proto/quivr/models/proposition.proto, proto/quivr/models/shared.proto
quivr protobuf questions rules
implement rules
Compile and publish
solve alls:  /**/ ask if we need len or max len rule**
https://topl.atlassian.net/browse/BN-833
=> BN-833-quivr-rules-proof-proposition-and-shared

proto/genus/genus_models.proto, proto/genus/genus_rpc.proto
Validation rules such as optional and non optional fields are added
Set the corresponding fields as optional on Genus protobuf files
Protobuf compiler runs correctly and the project structure looks correct.
* TSDK-317
=> TSDK-317 | Added validation rules to Genus

proto/brambl/models/box/box.proto, proto/brambl/models/box/lock.proto, proto/brambl/models/box/value.proto, proto/brambl/models/event.proto, proto/brambl/models/transaction/attestation.proto, proto/brambl/models/transaction/io_transaction.proto, proto/brambl/models/transaction/spent_transaction_output.proto, proto/brambl/models/transaction/unspent_transaction_output.proto, proto/quivr/models/proof.proto, proto/quivr/models/proposition.proto, proto/quivr/models/shared.proto
*
**Delete everything after and including this line after you are done reading and understand what to put for each section**
>### Purpose
>
>*State in plain words what the scope of the pull request and what problem it is trying to solve*
>
>### Approach
>
>*Enumerate the steps you took to create the code/changes contained in this pull request*
>
>### Testing
>
>*Specify all unit, integration, or end-to-end testing that is contained in this pull request*
>
>### Tickets
>
>*List tickets if any that are connected to this pull request in the following format:*
>
>_* closes #1234_
=> Protobuf model documentation

proto/node/models/p2p.proto
Adding the possibility to request and receive a response on known peers from a remote node
Added p2p.proto with appropriate request and response
By Bifrost node with local build protobuf
*
=> Added KnownHosts message

proto/brambl/models/address.proto, proto/genus/genus_models.proto, proto/genus/genus_rpc.proto
change name LockAddress
related to review comments: https://github.com/Topl/Bifrost/pull/2939
=> QueryByLockAddressRequest

proto/node/services/bifrost_rpc.proto
A new Node rpc service to checks mempool membership
ticket: BN-1025
=> BN-1025-node-checks-mempool-membership

proto/node/models/p2p.proto
Added ping and pong messages to measure network quality
Added appropriate protoboof messages 
By compiling messages itself
BN-1003
=> Added PingPong message

proto/node/models/p2p.proto
Fixing incorrect len string for ping pong message
Fixing incorrect len string for ping pong message
Fixing incorrect len string for ping pong message
*
=> Fixed incorrect string len for ping pong message

.github/workflows/_protoc_build.yml, build/dart/pubspec.lock, build/dart/pubspec.yaml, proto/brambl/models/box/value.proto, proto/node/models/node_config.proto
- GitHub "Deploy" Workflow is [failing](https://github.com/Topl/protobuf-specs/actions/runs/5281543928/jobs/9639922411)
- Still not sure why it fails on CI/CD (it succeeds for me locally)
- I suspect some recent updates to [protoc_plugin](https://pub.dev/packages/protoc_plugin/versions) caused a breaking change
- Update pubspec dependencies, GitHub Action dependencies
- :shrug: 
N/A
=> Update Dependencies, Remove Unused Imports

build/scala/build.sbt, build/scala/project/build.properties
upgrade scala 2.13.11 and sbt 1.9.0
=> upgrade scala 2.13.11 and sbt 1.9.0

.github/CODE_OF_CONDUCT.md, .github/workflows/deploy.yml, README.md
=> BM push snapshot on each commit / improve readme

.github/workflows/_protoc_build.yml, build/scala/build.sbt, build/scala/project/plugins.sbt, jitpack.yml
- scala 2/3 cross
-  I was able to consume it from BramblSC, https://github.com/Topl/BramblSc/tree/BN_scala_3
=> Bn scala 3

proto/brambl/models/box/value.proto, proto/node/models/ratio.proto
- This PR, create new models for a Transaction Update proposal
- These model will be used by Node-cli proposal step
- There are more fields that we should add, but I like to create the first iteration.
=> Bn 1159 proposal update

proto/brambl/models/box/value.proto
discussion: https://github.com/Topl/protobuf-specs/pull/78#discussion_r1307720927
=> groupId and SeriesId mandatory

proto/brambl/models/box/value.proto
Added field to proposal for slot gap during leader election
BN-1509
=> BN-1509 Added proposal for slot gap during leader election

proto/brambl/models/box/value.proto
Update eligibility gap to long instead of int
=> Bn 1509 add support for inserting a slot gap during leader election

proto/node/services/network_control.proto
Adding network control service
=> BN-1529 Add network control GRPC
